permalink: pretty

theme: jekyll_patternbot

patternbot:
  title: "Sebastian Turners Portfolio Website"
  description: |
    A porfolio collection of my school projects, client projects, and personal work.
  font_url: "https://fonts.googleapis.com/css?family=Cabin:400,400i,700,700i|Roboto:300,400,700&display=swap"
