title: "Sections"
description: |
  The descriptions are used to make up the body and main content of my website.

patterns:
  project-section:
    title: "Project Section"
    description: |
      The project section is only used on the main page to display my most highlighted portfolio pieces. When the pattern is used in succession it must alternate using field the "section_norm=true".
    fields:
      - name: section_norm
        type: string
        example: "true"
        required: false
  breakdown-section:
    title: "Breakdown Section"
    description: |
      The breakdown section is used on the project pages after the project banner. It is used to display the main content of the project.
